FROM node:18

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de configuración
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia los archivos del proyecto
COPY . .

# Expone el puerto
EXPOSE 3003

# Comando para iniciar el servicio
CMD ["node", "index.js"]
